package org.rootstock.hardware;

/**
 * HOW the goal-velocity argument of {@link MotorIO#setPositionGoal(double, double, double)} actually
 * reaches the motor.
 *
 * <p>This was a boolean once, and the boolean hid a real defect: the flagship Phoenix path claimed
 * {@code true} while calling {@code MotionMagicVoltage.withVelocity(...)}, a method that <b>does not
 * exist</b> — verified against the Phoenix 6 26.3.0 jar, zero matches. A boolean can only say "yes"
 * or "no"; the honest answer for Motion Magic is "yes, but through a different mechanism, with a
 * different failure mode, and {@link MotorIO#describe()} had better print which one".
 *
 * <p>The mechanism layer does <b>not</b> branch on this value — it always passes the term to the
 * seam, and the backend chooses the carrier. The value exists so that {@code describe()}, the
 * self-test and the field-locked-turret parity test can all name the path in use.
 */
public enum VelocityCarrier {

  /**
   * The vendor request has a real velocity REFERENCE field and the device's own closed loop consumes
   * it.
   *
   * <p>Phoenix {@code PositionVoltage.Velocity} is the example — "velocity to drive toward in
   * rotations per second, typically used for motion profiles generated by the robot program".
   * Highest fidelity: the term participates in the device's error computation, not just its output
   * sum.
   */
  NATIVE_REQUEST_FIELD,

  /**
   * No velocity field on the request, so the term is converted to VOLTS on the robot controller and
   * added to the request's arbitrary-feedforward field: {@code ff += kV_device * goalRps}.
   *
   * <p>{@code kV_device} is exactly the slot kV this library already computed ({@code kV_si *
   * siPerOutputRotation}), so the conversion introduces no new number and no new place for a unit
   * error.
   *
   * <p>This is the Motion Magic path. {@code MotionMagicVoltage}, {@code MotionMagicExpoVoltage} and
   * {@code DynamicMotionMagicVoltage} all have a feedforward field and none has a velocity field
   * (verified). Slightly lower fidelity than {@link #NATIVE_REQUEST_FIELD}: the device's velocity
   * error term does not see the offset, so steady-state tracking relies on the position loop plus
   * this open-loop volt term. For a field-locked turret that is the correct decomposition anyway.
   */
  DEVICE_FEEDFORWARD_VOLTS,

  /**
   * The backend has neither a velocity field nor an arbitrary-feedforward field on its position
   * request, so the mechanism folds the term into a roboRIO-side voltage trim before the seam call.
   *
   * <p>Reported, logged, and NEVER silently dropped. This is what a PWM controller and a fully
   * roboRIO-side loop report.
   */
  RIO_VOLTAGE_TRIM,

  /**
   * The backend genuinely cannot honour a non-zero goal velocity at all.
   *
   * <p>Setting one raises a FATAL config error at construction if the mechanism declares a
   * field-locked rotary axis, because a field-locked turret on such a backend is a feature that does
   * not work. No shipped backend returns this; it exists so that a future one cannot pretend.
   */
  UNSUPPORTED;

  /**
   * Whether a non-zero goal velocity survives the trip to the motor when this carrier is in use.
   *
   * @return true for everything except {@link #UNSUPPORTED}
   */
  public boolean delivers() {
    return this != UNSUPPORTED;
  }

  /**
   * Whether the backend itself carries the term, as opposed to the mechanism folding it into a
   * voltage before the seam call.
   *
   * @return true for {@link #NATIVE_REQUEST_FIELD} and {@link #DEVICE_FEEDFORWARD_VOLTS}
   */
  public boolean carriedByBackend() {
    return this == NATIVE_REQUEST_FIELD || this == DEVICE_FEEDFORWARD_VOLTS;
  }

  /**
   * One sentence naming the path, for {@link MotorIO#describe()} and for self-test output.
   *
   * @return a human-readable explanation with no trailing period
   */
  public String explanation() {
    return switch (this) {
      case NATIVE_REQUEST_FIELD ->
          "the goal velocity rides in the vendor request's own velocity field and the device's "
              + "closed loop consumes it";
      case DEVICE_FEEDFORWARD_VOLTS ->
          "the vendor request has no velocity field, so the goal velocity is converted to volts "
              + "(kV_device * goalRps) and added to the request's feedforward";
      case RIO_VOLTAGE_TRIM ->
          "the backend can carry neither a velocity nor a feedforward on its position request, so "
              + "the mechanism folds the goal velocity into a roboRIO-side voltage trim";
      case UNSUPPORTED ->
          "this backend cannot honour a non-zero goal velocity at all, so a field-locked axis on "
              + "it is a config error rather than a silent no-op";
    };
  }
}
